---
- hosts: all
  become: yes
  gather_facts: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Gnome DE
      package:
        name:
        - ubuntu-desktop
        state: present