---
- hosts: localhost
  connection: local

  vars:
    next_version_type: minor
    boxes:
      - ubuntu-2004
      - fedora-34
      - fedora-35
  
  tasks:
    - name: Init an empty dict for box versions
      set_fact:
        box_versions: {}
      tags: [never, version_check, debug]

    - name: Making boxes
      include_tasks: "tasks/build-box.yml"
      loop: "{{ boxes }}"
      loop_control:
        loop_var: box_name
      tags: [always]
    
    - name: Check new versions
      debug:
        var: box_versions
      tags: [never, version_check, debug]
    
    - name: Clean up output
      file:
        path: "box-files/{{ item }}/output/"
        state: absent
      loop: "{{ boxes }}"
      tags: [always, clean]