Vagrant.configure("2") do |config|
  config.vm.define "fedora35" do |config|
    config.vm.box = "fedora-35-desktop-workstation"
    config.vm.box  = "file://output/fedora-35/virtualbox/packer.box"
    config.vm.provider "virtualbox" do |v|
      v.gui = true
      v.check_guest_additions = false
      v.cpus = 2
      v.memory = 8192
      v.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
      v.customize ["modifyvm", :id, "--accelerate3d", "on"]
    end
  end
end